### ISSUE TITLE
Clarify units of motion for PWM3901 output

### ISSUE THREAD

**Issue by cconway** [bitcraze/Bitcraze_PMW3901#2]
I haven't been able to find any information in the data sheets to explain how a user converts the "motion counts" into a measurable distance. It would be nice if the documentation could be expanded to give a rough explanation of what the motion counts mean and how they could be referenced to a unit of distance.

**Comment by ataffanel** [comment]
Unfortunately this is not documented in the Datasheet. For the Crazyflie, we have experimentally devised the equation to convert the output of the sensor in distance. The algorithm we are using in the Crazyflie is described in [Marcus Greiff's Master thesis](http://lup.lub.lu.se/luur/download?func=downloadFile&recordOId=8905295&fileOId=8905299) section 6.5. The implementation is part or the [Crazyflie kalman filter](https://github.com/bitcraze/crazyflie-firmware/blob/6308ff47ff4d4691f9b7f6f991564244c76d7910/src/modules/src/estimator_kalman.c#L1034-L1098).

I will update the readme of this project with these links since this is the best we have so far.
